services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
  nlpserver:
    build:
      context: ./nlpserver
      dockerfile: Dockerfile
  nlpc:
    depends_on:
      - nlpserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001

volumes:
  pgdata-dev:
